11:39:14,966 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
11:39:14,994 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:40597/], count 0
11:39:14,996 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:40597/], count 0
11:39:15,88 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
12:17:41,156 rospy.core INFO signal_shutdown [atexit]
12:17:41,163 rospy.internal INFO topic[/rosout] removing connection to /rosout
12:17:41,164 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
12:17:41,164 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:40597/
12:17:41,164 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:40597/
12:17:41,170 rospy.impl.masterslave INFO atexit
12:17:46,604 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:40315/], count 0
12:17:46,605 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:40315/], count 0
12:17:46,666 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
12:17:46,761 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
12:18:08,256 rospy.core INFO signal_shutdown [atexit]
12:18:08,267 rospy.internal INFO topic[/rosout] removing connection to /rosout
12:18:08,268 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
12:18:08,271 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:40315/
12:18:08,272 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:40315/
12:18:08,272 rospy.impl.masterslave INFO atexit
12:18:08,275 rospy.internal ERROR Unable to initiate TCP/IP socket to simone-Aspire-V3-772G:39357 (http://simone-Aspire-V3-772G:40315/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

12:18:08,277 rospy.internal ERROR Unable to initiate TCP/IP socket to simone-Aspire-V3-772G:39357 (http://simone-Aspire-V3-772G:40315/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

13:41:15,14 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
13:41:15,34 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:33957/], count 0
13:41:15,41 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:33957/], count 0
13:41:15,137 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
13:42:19,22 rospy.core INFO signal_shutdown [atexit]
13:42:19,30 rospy.internal INFO topic[/rosout] removing connection to /rosout
13:42:19,32 rospy.internal ERROR Unable to initiate TCP/IP socket to simone-Aspire-V3-772G:41099 (http://simone-Aspire-V3-772G:33957/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

13:42:19,32 rospy.internal ERROR Unable to initiate TCP/IP socket to simone-Aspire-V3-772G:41099 (http://simone-Aspire-V3-772G:33957/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

13:42:19,32 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
13:42:19,33 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:33957/
13:42:19,33 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:33957/
13:42:19,33 rospy.impl.masterslave INFO atexit
14:48:40,338 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
14:48:40,341 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:40639/], count 0
14:48:40,342 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:40639/], count 0
14:48:40,535 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
14:49:26,939 rospy.core INFO signal_shutdown [atexit]
14:49:26,954 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:34495 (http://simone-Aspire-V3-772G:40639/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

14:49:26,954 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:40639/
14:49:26,954 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:34495 (http://simone-Aspire-V3-772G:40639/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

14:49:26,954 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:40639/
14:49:26,958 rospy.internal INFO topic[/rosout] removing connection to /rosout
14:49:26,958 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
14:49:26,958 rospy.impl.masterslave INFO atexit
14:49:32,346 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:35249/], count 0
14:49:32,348 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:35249/], count 0
14:49:32,351 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
14:49:32,432 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
14:49:41,472 rospy.core INFO signal_shutdown [atexit]
14:49:41,488 rospy.internal INFO topic[/rosout] removing connection to /rosout
14:49:41,489 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
14:49:41,489 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:35249/
14:49:41,490 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:35249/
14:49:41,490 rospy.impl.masterslave INFO atexit
14:49:41,490 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:38809 (http://simone-Aspire-V3-772G:35249/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
rosgraph.network.ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

14:51:33,73 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
14:51:33,151 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:37823/], count 0
14:51:33,153 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:37823/], count 0
14:51:33,248 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
14:52:44,60 rospy.core INFO signal_shutdown [atexit]
14:52:44,66 rospy.internal INFO topic[/rosout] removing connection to /rosout
14:52:44,66 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
14:52:44,66 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:37823/
14:52:44,67 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:37823/
14:52:44,67 rospy.impl.masterslave INFO atexit
